### PR TITLE
 add doc generation to ci

### PR DESCRIPTION
**Pull request by behrica**
The CI build only triggers when open a PR.
So I just test the automatic doc creation.

Don't merge yet

### CODE REVIEW

**Comment by behrica** [comment]
It works now.
I needed to do a lot of commits, to trigger the build.

Best you squash them into one, if you merge it

**Comment by behrica** [comment]
We need to re-think the handling of the "docs" folder.
In an automatic creation of its content,as we have it with this PR, it makes no sense that "docs" is even in version control.

GitHub as ways to generate the same GitHub pages from inside a GitHub action, and that we should do.
Then the docs folder would not be anymore in version control.

**Comment by behrica** [comment]
But I propose to have this on an other PR

**Comment by daslu** [comment]
Hi @behrica, looks very nice.

I am not experienced with github actions, so I don't know how difficult it is to optimize.

It looks like a lot of unnecessary work is done on every code change. Most code changes will be small fixes to existing tutorials. They do not affect the library dependencies, and thus should not break the tests, except for maybe their own tests. 

So we are coupling a lot of things in one big run. Maybe it means we should structure the project differently to remove this coupling.

**Comment by behrica** [comment]
I still don't understand why you care about unnecessary work. GitHub actions don't cost anything.
Even executing them various times a day is not a problem. Each run takes a few minutes. 

A lot of open source projects do this.

For example,  the full vega lite website is automatically generated on each change.
Reorganize this would be a lot of work and ultimately fail to take care on all dependencies.

What we can do is to have a different branching strategy. So changes don't go to main, but to dev and certain github tasks don't execute on dev.

**Comment by behrica** [comment]
The key issues with is this:
https://github.com/orgs/community/discussions/21582

It's very hard to preview changes to the GitHub pages in cases of branches and PRs.

Only possible locally by checking out the PR and building the docs locally.

**Comment by behrica** [comment]
Most changes I did are for debugging the devcontainer/github action.
I had difficulties to have the empty .venv folder and the fact that some devcontainer setup task run asynchronously. 
These could removed, once it works on main

**Comment by behrica** [comment]
To me it should work know when merged.

So on each commit to main,
- all tests should be generated 
- all tests should be executed
- docs get build
- GitHub page is updated 

Any failure will stop the flow.

**Comment by behrica** [comment]
One question on this is if the doc generation should trigger on PRs / changes on PRs.

Probably not as this would only update the PR branch with the new docs.

But this will never be rendered on line, as we render docs from 'main' only.

This would need two workflow files with different triggers.

This would make the github actions simpler.

Auto-commit to PR branches seem complicated.

**Comment by daslu** [comment]
Thanks for explaining.

To be sure I understand:
* If anything fails, the whole process is canceled (so docs are not updated).
* But we can still update the docs manually by pushing changes to the `docs` directory (in case we need to add an important comment before we fix the failure).

Is that right?

**Comment by behrica** [comment]
> Thanks for explaining.
> 
> To be sure I understand:
> 
> * If anything fails, the whole process is canceled (so docs are not updated).
> * But we can still update the docs manually by pushing changes to the `docs` directory (in case we need to add an important comment before we fix the failure).
> 
> Is that right?

I have decided at a certain point 2 have 2 "jobs", "build incl. tests" and "make docs"
Jobs run in parallel, so failure of one does not affect the other.

We could revert this again, it was all "try/error" as I could not get it working.

So currently, test failure will not prevent doc update.

Yes, manul commits  to main in "docs/" will re-publish.
(this might get overridden by "make docs" action)
(so its not a good idea to do this)

The workflow should be:
- test doc / code changes localy including local build / make docs
- commit and push code changes (not docs/ changes)

Maybe there is something to adapt. A "local make docs" might change files in docs.

It should not matter to push those changes, the GitHub action might override them (but being the same)
I don't know if the doc generation produces always the same files character by character, or is there some "random" variation (timestamps for example)

In any case the build will re-generate all docs and it will render which "it" generated.
So from a "user" point of view,
it should not matter if / if not you commit/push local change to docs/.
(assuming that you always commit/push changes to the clj files)

What should be avoid is "Only commit/push" changes to docs/.
and leave changes to clj files local.

**Comment by behrica** [comment]
Ideally the docs/ folder would not be on the "main" branch and more and part of  .gitignore
There are several ways to do so (either a specific branch to which they get commited by teh action, or integrate actions which "copy directly" to the GitHub pages.

Then changes to the GitHub page can only be achieved by changing clj files.

**Pull request merged**
