### PR TITLE
Add model reference docu

### PR DESCRIPTION
**Pull request by behrica**
content wise I am done.
I migrated the existing "reference" documentation of models from smile , xgboost and sklearn-clj

I am not sure, if my layout changes are fine for all screen sizes, see in clay.edn.
For sure, the so far default was far too small for my new content

### CODE REVIEW

**Comment by behrica** [comment]
to me I am done.
I marked the new chapters as draft

**Comment by daslu** [comment]
@behrica 

Great.

I cannot read so carefully now, so I'd recommend merging this as a draft, as we discussed.

One thing that seems important to me is not to hide the namespace definitions, so that the tutorials will be self-contained.

**Comment by behrica** [comment]
I will rebase it now.

**Comment by behrica** [comment]
>One thing that seems important to me is not to hide the namespace definitions, so that the tutorials will be self-contained.
What do you mean ?
I did hide now the ns declarations, 
but this does not make it self contained (not even sure what you mean by this)

This makes it "visualy nicer" to look at, but not more then that.

**Comment by behrica** [comment]
Its true, I will have a look.
some of the reference ns have "no example", so there we should see no code at all.
But some have indeed

**Comment by daslu** [comment]
Thanks

**Comment by behrica** [comment]
The "draft" is in the "chapter", bu not in the TOC
not sure why

**Comment by behrica** [comment]
now it is..

**Pull request merged**
