### PR TITLE
small fixes to automl notebook

### PR DESCRIPTION
**Pull request by behrica**

### CODE REVIEW

**Comment by daslu** [comment]
Hi @behrica, nice additions.

I think this PR goes beyond small fixes and requires discussion.

I don't think it makes sense to add dependencies to the `:dev` alias, except for tooling (e.g., Clay).

The goal of the tutorials is to test and document the integration of the libraries in the main deps. If we want `scicloj.ml.smile` and `sklearn-clj` in the tutorials, we need to decide whether they are part of Noj.

`sklearn-clj` seems harmless.
`scicloj.ml.smile` may be ok but needs testing.

But let us discuss this at Zulip and then have a dedicated PR to add the relevant libraries to the main deps?

**Comment by behrica** [comment]
I have an other PR to add integration-test, without notebook.
This would clean-up the deps.edn as you asked as well.

Maybe merge this first, and then I rebase against main.
Or if you prefer, put this on a 'dev' branch or similar

**Comment by daslu** [comment]
Thanks, @behrica. I'm merging now.

**Comment by daslu** [comment]
@behrica probably it'd also make sense to remove the `python.edn` file you've added, right?

Or are you proposing to standardize its use somehow?

**Comment by behrica** [comment]
> @behrica probably it'd also make sense to remove the `python.edn` file you've added, right?
> 
> Or are you proposing to standardize its use somehow?

Some of the notebooks use libpython-clj, which is using this file if present.
So it is an artifact needed for the "tests".
It should not go (and will not) go into the jar of noj.

**Comment by behrica** [comment]
the failing tests are "unexpected failures" to me.
I was not working in "that area".
I check them now on main branch.

**Pull request merged**
