### PR TITLE
added tribuo trainer / component references

### PR DESCRIPTION
**Pull request by behrica**

### CODE REVIEW

**Comment by daslu** [comment]
@behrica This is brilliant.

As usual, I'd suggest marking this as `"DRAFT 🛠"` and merging.
After we add a few paragraphs explaining how to use these components and how to read the reference, we can remove the draft note.

Sounds good?

**Review by daslu — COMMENTED** [review]
(added a comment above)

**Comment by behrica** [comment]
For me  a reference is not Draft, it's done.Its autogenerated.
Tribuo example are somewhere else already.
Maybe we could add somewhere to mention the 3 model plugins and point to the reference.
In ml-basic for example

**Comment by abhi18av** [comment]
Thanks for this @daslu  and @behrica !

**Pull request merged**
